flaskaccounts/views/newuser.py
from flask import Blueprint,render_template,g,request,redirect,url_for,session,flash
import bcrypt

newuser=Blueprint('newuser',__name__)

@newuser.route('/register',methods=['GET','POST'])
def register():
    error='';userlist=[];newuser=''
    if request.method=='POST':
        newuser=request.form['username']
        userlist=[username for username, in g.db.execute('SELECT username from users')]
        #for row in g.db.execute('SELECT username from users'):
        #    username,=row
        #    userlist.append(str(username))
        if newuser in userlist:
            error='Username exists. Pick another username'
            flash(error)
        else:
            flash('Success')
            session['username']=newuser
            return redirect(url_for('.register_pw'))
    return render_template('users/register.html',error=error,userlist=userlist,newuser=newuser)

@newuser.route('/register_pw')
def register_pw():
    currentuser=''
    try:
        currentuser=session['username']
    except KeyError:
        return redirect(url_for('existinguser.login'))
    userlist=[username for username, in g.db.execute('SELECT username from users')]
    if currentuser in userlist:
        return redirect(url_for('display.listall'))
    return render_template('users/register_pw.html',currentuser=currentuser)

flaskaccounts/templates/users/login.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>Sign In to Proceed</h1>
</div>

<form action="{{url_for('existinguser.login')}}" method=POST>
<input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
<input type="password" name="password" class="form-control" placeholder="password" required>


<button type="submit" class="btn btn-primary" value="Submit">Log In</button>
<a href="{{url_for('newuser.register')}}" class="btn btn-info">Register</a>

{{ form.csrf_token }}
</form>

{%if error%}
<br><br>
<h3 class="bg-danger"><em>{{error}}</em></h3>
{%endif%}

{%for message in flashed_messages%}
<br><br>
<h3 class="bg-success"><em>{{message}}</em></h3>
{%endfor%}

{% endblock %}

flaskaccounts/templates/users/register.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>New User</h1>
</div>

<form action="{{url_for('newuser.register')}}" method=POST>
<input type="text" name="username" class="form-control" placeholder="Pick a Username" required autofocus>
<!--<input type="password" name="password" class="form-control" placeholder="password" required>-->


<button type="submit" class="btn btn-info" value="Submit">Next</button>
</form>

{%if error%}
<!--<br><br>
<h3 class="bg-danger"><em>{{error}}</em></h3>-->
{%endif%}

{% with messages = get_flashed_messages() %}
    {%if messages%}
    {%for message in messages%}
    <br><br>
    <h3 class="bg-success"><em>{{message}}</em></h3>
    {%endfor%}
    {%endif%}
{%endwith%}

{% endblock %}

flaskaccounts/templates/users/register_pw.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>{{currentuser}} : Enter Password</h1>
</div>

<form action="{{url_for('newuser.register_pw')}}" method=POST>
<input type="password" name="password" class="form-control" placeholder="Password" required autofocus>
<input type="password" name="password2" class="form-control" placeholder="Confirm Password" required autofocus>
<!--<input type="password" name="password" class="form-control" placeholder="password" required>-->


<button type="submit" class="btn btn-info" value="Submit">Next</button>
</form>

{%if error%}
<!--<br><br>
<h3 class="bg-danger"><em>{{error}}</em></h3>-->
{%endif%}

{% with messages = get_flashed_messages() %}
    {%if messages%}
    {%for message in messages%}
    <br><br>
    <h3 class="bg-success"><em>{{message}}</em></h3>
    {%endfor%}
    {%endif%}
{%endwith%}

{% endblock %}