flaskaccounts/views/display.py
from flask import Blueprint,render_template,g,request,redirect,url_for,session
from flask.ext.login import login_required
from flask.ext.login import current_user

display=Blueprint('display',__name__)

@display.route('/show',defaults={'no_rows_limit':None})
@display.route('/show/<int:no_rows_limit>')
@login_required
def listall(no_rows_limit):
	#return render_template('body.html')
	dictionary={}
	#if session['logged_in']==False:
	#	return redirect(url_for('existinguser.login'))


	for row in g.db.execute('SELECT * FROM ENTRIES'):
		(ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
		dictionary[ID]=[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]
		max_rows=len(dictionary)

		if no_rows_limit!=None:
			min_row=max_rows-no_rows_limit
		else:
			min_row=0
	return render_template('display/main.html',output=dictionary,min_row=min_row,username=current_user.username,state2="active")

@display.route('/filter',methods=['POST'])
@login_required
def filter1():
	#if session['logged_in']==False:
	#	return redirect(url_for('existinguser.login'))
	if request.method=='POST':
		dictionary={}
		for row in g.db.execute('SELECT * FROM ENTRIES'):
			keyword=str(request.form['keyword'])
			(ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
			if keyword in DESCRIPTION.lower():
				dictionary[ID]=[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]

		return render_template('display/main.html',output=dictionary,min_row=0,username=current_user.username,state2="active",keyword=keyword)

@display.route('/sortdate',defaults={'no_rows':None})
@display.route('/sortdate/<int:no_rows>')
@login_required
def sortdate(no_rows):
	#if session['logged_in']==False:
	#	return redirect(url_for('existinguser.login'))

	dictionary={};dictionary2={}
	for row in g.db.execute('SELECT * FROM ENTRIES'):
		(ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
		datesort=int(YEAR)*10000+int(MONTH)*100+DAY
		dictionary.setdefault(datesort,[]).append({ID:[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]})

		if no_rows!=None:
			min_row=0
		else:
			min_row=0

	return render_template('display/datesort.html',output=dictionary,no_rows=min_row,username=current_user.username,state4="active")

flaskaccounts/views/existinguser.py
from flask import Blueprint,render_template,g,request,redirect,url_for,session,flash,current_app
import bcrypt
from flask.ext.login import login_user,logout_user
from ..forms import UserPWForm
from ..model import User
from flask.ext.login import current_user

existinguser=Blueprint('existinguser',__name__)

@existinguser.route('/login',methods=['GET','POST'])
def login():
	form=UserPWForm()
	error=None
	if form.validate_on_submit():
		username=form.username.data
		password=form.password.data

		user=User(username,current_app.config['DATABASE'])
		if user.is_anonymous()==True:
			error='Unregistered User'
		else:
			user.authenticate(password)
			if user.is_authenticated0==True:
				login_user(user)
				#next = flask.request.args.get('next')

				#session['username']=username
				#session['logged_in']=True

				return redirect(url_for('display.listall',no_rows_limit=20))
			else:
				error='Password Does Not Match'
		'''for row in g.db.execute('SELECT username,hashed from users where username=?',[str(username)]):
			usernames,hashed=row
			#userdict[usernames]=hashed

		if 'usernames' not in globals():
			error='Unregistered User'

		else:
			hashedresult=bcrypt.hashpw(password,hashed)
			if hashedresult==str(hashed):
				session['logged_in']=True
				#session['username']=username
				flash('Log In Successful')
				return redirect(url_for('display.listall',no_rows_limit=20))
			else:
				error='Password Does Not Match'''

	return render_template('users/login.html',error=error,form=form)

@existinguser.route('/logout',methods=['GET','POST'])
def logout():
	logout_user()
	#session['logged_in']=False
	#session.pop('username',None)
	return redirect(url_for('.login'))
	#return render_template('')

flaskaccounts/views/summary.py
from flask import Blueprint,render_template,g,request,redirect,url_for,session
from flask.ext.login import LoginManager,login_required,current_user

summarize=Blueprint('summarize',__name__)

@summarize.route('/')
@summarize.route('/summary')
@login_required
def getsummary():
	accounts={}
	for row in g.db.execute('select account,sum(amount) as sum from entries group by account having sum!=0'):
		account,total=row
		accounts[account]=total

	return render_template('summary/summary2.html',accounts=accounts,state3='active',username=current_user.username)

flaskaccounts/templates/add.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>Add Entry</h1>
</div>
<form role="form" class="form-inline" action="{{url_for('add_entry')}}" method=POST>

<div class="form-group">

	<div class="input-group" style="width:10em">
			<span class="input-group-addon" id="date"">Date</span>
			<input type="date" aria-describedby="date" placeholder="dd/mm/yy" name="date" style="width:10em">
	</div>

	<div class="input-group">
			<span class="input-group-addon" id="account"">Account</span>
			<select class="form-control" name="account">
			{%for account in accounts|sort%}
			<option value="{{account}}">{{account}}</option>
			{%endfor%}
			<!--<option value="PREMIER">PREMIER</option>
			<option value="ADVANCED">ADVANCED</option>
			<option value="SAVINGS">SAVINGS</option>
			<option value="DSARA GROUNDWORKS">DSARA GW</option>
			<option value="DSARA PILING">DSARA PILING</option>-->
			
			</select>
	</div>

	<div class="input-group">
			<span class="input-group-addon" id="description"">Description</span>
			<input type="text" aria-describedby="description" placeholder="E.g. June Salary" name="description">
	</div>

	<div class="input-group" style="width:7em">
			<span class="input-group-addon" id="amount"">Amount</span>
			<input type="number" step="any" aria-describedby="amount" placeholder="999.99" name="amount" style="width:7em">
	</div>

	
	
	<div class="input-group">
			<span class="input-group-addon" id="description"">Currency</span>
			<select class="form-control" name="currency">
			<option value="GBP">GBP</option>
			<option value="MYR">MYR</option>
			</select>
	</div>

<br><br><button type="submit" class="btn btn-primary" value="Submit">Add</button>
</div>

</form>

<h1>{{test}}</h1>
{% endblock %}

flaskaccounts/templates/body.html
{% extends "layout.html" %}
{% block body %}

{% endblock %}

flaskaccounts/templates/convert.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>Currency Conversion Entry</h1>
</div>
{{date}}
<form role="form" class="form-inline" action="{{url_for('convert')}}" method=POST>

<div class="form-group">

	<div class="input-group" style="width:10em">
			<span class="input-group-addon" id="date"">Date</span>
			<input type="date" aria-describedby="date" placeholder="dd/mm/yy" name="date" style="width:10em">
	</div>

	<br><br>
	<div class="input-group">
			<span class="input-group-addon" id="fromaccount"">From Account</span>
			<!--<input type="text" aria-describedby="account" placeholder="PREMIER" name="account" style="width:12em">-->
			<select class="form-control" name="fromaccount">
			<option value="PREMIER">PREMIER</option>
			<option value="ADVANCED">ADVANCED</option>
			<option value="SAVINGS">SAVINGS</option>
			<option value="DSARA GROUNDWORKS">DSARA GW</option>
			<option value="DSARA PILING">DSARA PILING</option>
			</select>
	</div>

	<div class="input-group">
			<span class="input-group-addon" id="toaccount"">To Account</span>
			<!--<input type="text" aria-describedby="account" placeholder="PREMIER" name="account" style="width:12em">-->
			<select class="form-control" name="toaccount">
			<option value="PREMIER">PREMIER</option>
			<option value="ADVANCED">ADVANCED</option>
			<option value="SAVINGS">SAVINGS</option>
			<option value="DSARA GROUNDWORKS">DSARA GW</option>
			<option value="DSARA PILING">DSARA PILING</option>
			</select>
	</div>

	<br><br>
	

	<div class="input-group">
			<span class="input-group-addon" id="amount"">Amount</span>
			<input type="number" step="any" aria-describedby="amount" placeholder="999.99" name="amount">
	</div>

	
	<br><br>
	<div class="input-group">
			<span class="input-group-addon" id="description"">Currency</span>
			<select class="form-control" name="currency">
			<option value="GBP">GBP</option>
			<option value="MYR">MYR</option>
			</select>
	</div>
	
	<div class="input-group" >
			<span class="input-group-addon" id="rate"">Rate</span>
			<input type="number" step="any" aria-describedby="rate" placeholder="5.5" name="rate">
	</div>


<br><br><button type="submit" class="btn btn-primary" value="Submit">Add</button>
</div>

</form>

<h1>{{test}}</h1>
{% endblock %}

flaskaccounts/templates/layout.html
<!DOCTYPE html>
<head>
<title>Flask Accounts</title>
<meta charset="utf-8">
<meta http-equiv='cache-control' content='no-cache'>
<meta http-equiv='pragma' content='no-cache'>
<meta name="viewport" content="width=device width, initial-scale=1">



<link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}">



<link rel="stylesheet" href="{{url_for('static',filename='bootstrap-theme.min.css')}}">


<script src="{{url_for('static',filename='jquery.min.js')}}"></script>
<script src="{{url_for('static',filename='bootstrap.min.js')}}"></script>




</head>

<!--------------------------------------------------------------------------------------------------------------------------------->

<nav class="navbar navbar-inverse">
<div class="container-fluid">
	<div class="navbar-header">
	<a class="navbar-brand" href="{{url_for('display.listall',no_rows_limit=20)}}">FlaskAccounts</a>
	</div>

	<div id="navbar">
		<ul class="nav navbar-nav">
		    {%if username%}
			<li class="dropdown">
				<a class="dropdown-toggle {{state2}}" data-toggle="dropdown" href="#">ID sort<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="{{url_for('display.listall',no_rows_limit=20)}}">20 Entries</a></li>
					<li><a href="{{url_for('display.listall')}}">All Entries</a></li>
				</ul>
			</li>
			<li class="{{state4}}"><a href="{{url_for('display.sortdate',no_rows=20)}}">Date Sort</a></li>
			<li class="{{state3}}"><a href="{{url_for('summarize.getsummary')}}">Summary</a></li>
			{%endif%}
		</ul>

		{%if username%}
		<ul class="nav navbar-nav navbar-right">
			<li><a href="#">Current user: <em>{{username}}</em></a></li>
			<li><a href="{{url_for('existinguser.logout')}}">Logout</a></li>
		</ul>
		{%endif%}

	</div>
</div>
</nav>


<!--------------------------------------------------------------------------------------------------------------------------------->

<div class="container">
<!--<p>Current user: <em>{{username}}</em>    <a href="{{url_for('existinguser.logout')}}" class="btn btn-default btn-sm">Logout</a></p>-->
{% block body %}{% endblock %}
</div>

</html>

flaskaccounts/templates/login.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>Sign In to Proceed</h1>
</div>

<form action="{{url_for('login')}}" method=POST>
<input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
<input type="password" name="password" class="form-control" placeholder="password" required>


<button type="submit" class="btn btn-primary" value="Submit">Log In</button>
</form>

{%if error%}
<br><br>
<h3 class="bg-danger"><em>{{error}}</em></h3>
{%endif%}

{%for message in flashed_messages%}
<br><br>
<h3 class="bg-success"><em>{{message}}</em></h3>
{%endfor%}

{% endblock %}

flaskaccounts/templates/main.html
{% extends "layout.html" %}
{% block body %}

<div class="page-header">
<h1>Entries sorted by ID</h1>
	<form action="{{url_for('filter1')}}" method=POST>
	<div class="input-group">
		<input type="text" name="keyword" class="form-control" placeholder="Filter by keyword...">
		<span class="input-group-btn"><button class="btn btn-default" type="submit" value="submit">Filter</button></span>
	</div>
	</form>
</div>

{%if keyword%}
<h5>Filtered by keyword: <em>{{keyword}}</em></h5>
{%endif%}

<table class="table table-condensed table-bordered">

<thead>
<tr>
<th>Date</th>
<th>Account</th>
<th>Description</th>
<th>Amount</th>
<th>Currency</th>
</tr>
</thead>

<tbody>
{%for id in output.keys()[min_row:]|sort%}
{%if output[id][3]=='PREMIER' %}
<tr class="info">
{%elif output[id][3]=='ADVANCED'%}
<tr class="danger">
{%elif output[id][3]=='SAVINGS'%}
<tr class="success">
{%else%}
<tr>
{%endif%}
<td>{{'%s/%s/%s'%(output[id][2],output[id][1],output[id][0])}}</td>
<td>{{output[id][3]}}</td>
<td>{{output[id][6]}}</td>
<td>{{output[id][4]}}</td>
<td>{{output[id][5]}}</td>
<td><a href="{{url_for('edit_entry',id_no=id)}}">Edit</a></td>
<td><a href="{{url_for('delete_entry',id_no=id)}}">Delete</a></td>
</tr>
{%endfor%}
</tbody>
</table>

<a href="{{url_for('add_entry')}}{{a}}" role="button" class="btn btn-primary">Add</a>
<a href="{{url_for('convert')}}{{a}}" role="button" class="btn btn-primary">Convert currency</a>
<a href="{{url_for('transfer')}}{{a}}" role="button" class="btn btn-primary">Transfer</a>

{% endblock %}

flaskaccounts/templates/transfer.html
{% extends "layout.html" %}
{% block body %}
<div class="page-header">
<h1>Transfer</h1>
</div>
{{date}}
<form role="form" class="form-inline" action="{{url_for('transfer')}}" method=POST>

<div class="form-group">

	<div class="input-group" style="width:10em">
			<span class="input-group-addon" id="date"">Date</span>
			<input type="date" aria-describedby="date" placeholder="dd/mm/yy" name="date" style="width:10em">
	</div>

	<br><br>
	<div class="input-group">
			<span class="input-group-addon" id="fromaccount"">From Account</span>
			<!--<input type="text" aria-describedby="account" placeholder="PREMIER" name="account" style="width:12em">-->
			<select class="form-control" name="fromaccount">
			{%for account in accounts|sort%}
			<option value="{{account}}">{{account}}</option>
			{%endfor%}	
			</select>
	</div>

	<div class="input-group">
			<span class="input-group-addon" id="toaccount"">To Account</span>
			<select class="form-control" name="toaccount">
			{%for account in accounts|sort%}
			<option value="{{account}}">{{account}}</option>
			{%endfor%}			
			<!--<option value="PREMIER">PREMIER</option>
			<option value="ADVANCED">ADVANCED</option>
			<option value="SAVINGS">SAVINGS</option>
			<option value="DSARA GROUNDWORKS">DSARA GW</option>
			<option value="DSARA PILING">DSARA PILING</option>-->
			</select>
	</div>

	<br><br>
	

	<div class="input-group">
			<span class="input-group-addon" id="amount"">Amount</span>
			<input type="number" step="any" aria-describedby="amount" placeholder="999.99" name="amount">
	</div>

	
	<br><br>
	<div class="input-group">
			<span class="input-group-addon" id="description"">Currency</span>
			<select class="form-control" name="currency">
			<option value="GBP">GBP</option>
			<option value="MYR">MYR</option>
			</select>
	</div>

	<br><br>

	<div class="input-group">
			<span class="input-group-addon" id="description"">Description</span>
			<input type="text" aria-describedby="description" placeholder="E.g. June Salary" name="description">
	</div>

<br><br><button type="submit" class="btn btn-primary" value="Submit">Add</button>
</div>

</form>

<h1>{{test}}</h1>
{% endblock %}