flaskaccounts/views/controller.py
from flask import Blueprint,render_template,g,request,redirect,url_for,session
from flask.ext.login import login_required
from flask.ext.login import current_user

controller=Blueprint('controller',__name__)

#To-do. Move this to the database.
#accounts={'PREMIER':'PREMIER','ADVANCED':'ADVANCED','SAVINGS':'SAVINGS','TIME DEPOSITS':'TIME DEPOSITS','DSARA GW':'DSARA GROUNDWORKS','DSARA PL':'DSARA PILING','CASH':'CASH','DSARA IN':'DSARA IN'}
#accounts=['PREMIER','ADVANCED','SAVINGS','TIME DEPOSITS']
currencylist=['GBP','MYR']

@controller.route('/add',methods=['GET','POST'])
@login_required
def add_entry():
    accounts=[]
    #if session['logged_in']==False:
    #    return redirect(url_for('users.login',username=session['username']))

    if request.method=='GET':
        #return render_template('controls/add.html',accounts=accounts)
	for row in g.db.execute("SELECT username,account FROM ACCOUNTNAME where username=?",[current_user.username]):
            username,account=row
            accounts.append(str(account.upper()))
        return render_template('controls/add.html',accounts=accounts)

    elif request.method=='POST':
        date=request.form['date']
	#return render_template('controls/add.html',date=date)
	(year,month,day)=date.split('-')
	account=request.form['account']
	amount=request.form['amount']
	description=request.form['description']
	currency=request.form['currency']
	if len(str(year))<4:
		year=2000+int(year)

	g.db.execute('INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(?,?,?,?,?,?,?)',[int(year),int(month),int(day),account,amount,currency,description])
	g.db.commit()
	return redirect(url_for('display.listall',no_rows_limit=20))

@controller.route('/convert',methods=['GET','POST'])
@login_required
def convert():
    #if session['logged_in']==False:
    #    return redirect(url_for('users.login'))

    if request.method=='GET':
	return render_template('controls/convert.html',username=current_user.username)
    elif request.method=='POST':
	date=request.form['date']
	(year,month,day)=date.split('-')
	fromaccount=request.form['fromaccount']
	toaccount=request.form['toaccount']
	amount=float(request.form['amount'])*-1
	rate=request.form['rate']
	amount_conv='%.2f'%(float(rate)*float(amount)*-1)
	currency1='GBP'
	currency2='MYR'
	description='GBP to MYR @ %s'%(str(rate))

	#First entry. From premier
	g.db.execute('INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(?,?,?,?,?,?,?)',[int(year),int(month),int(day),fromaccount,amount,currency1,description])
	g.db.execute('INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(?,?,?,?,?,?,?)',[int(year),int(month),int(day),toaccount,amount_conv,currency2,description])
	g.db.commit()
	return redirect(url_for('display.listall',no_rows_limit=20))

@controller.route('/transfer',methods=['GET','POST'])
@login_required
def transfer():
    accounts=[]
    #if session['logged_in']==False:
	#return redirect(url_for('users.login'))

    if request.method=='GET':
        for row in g.db.execute("SELECT username,account FROM ACCOUNTNAME where username=?",[current_user.username]):
            username,account=row
            accounts.append(str(account.upper()))
	return render_template('controls/transfer.html',accounts=accounts,username=current_user.username)

    elif request.method=='POST':
        date=request.form['date']
	(year,month,day)=date.split('-')
	fromaccount=request.form['fromaccount']
        toaccount=request.form['toaccount']
	amount=float(request.form['amount'])*-1
	amount2=float(request.form['amount'])
	currency=request.form['currency']
	description=request.form['description']
	#First entry. From premier
	g.db.execute('INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(?,?,?,?,?,?,?)',[int(year),int(month),int(day),fromaccount,amount,currency,description])
	g.db.execute('INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(?,?,?,?,?,?,?)',[int(year),int(month),int(day),toaccount,amount2,currency,description])
	g.db.commit()

	return redirect(url_for('display.listall',no_rows_limit=20))

@controller.route('/delete/<int:id_no>')
@login_required
def delete_entry(id_no):
    #if session['logged_in']==False:
	#return redirect(url_for('login'))
    g.db.execute('DELETE FROM ENTRIES WHERE ID=?',[id_no])
    g.db.commit()
    return redirect(url_for('display.listall',no_rows_limit=20))

@controller.route('/edit/<int:id_no>',methods=['GET','POST'])
@login_required
def edit_entry(id_no):
    accounts=[]
    #if session['logged_in']==False:
	#return redirect(url_for('users.login'))
    if request.method=='GET':
        for row in g.db.execute("SELECT username,account FROM ACCOUNTNAME where username=?",[current_user.username]):
            username,account=row
            accounts.append(str(account.upper()))
	for row in g.db.execute('SELECT * FROM ENTRIES WHERE ID=?',[id_no]):
            (ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
            rowlist=[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]
            #         0    1     2     3      4      5         6
        return render_template('controls/edit.html',rowlist=rowlist,accounts=accounts,id1=id_no,currency=currencylist,username=current_user.username)
    elif request.method=='POST':
	date=request.form['date']
	#return render_template('controls/add.html',date=date)
	(year,month,day)=date.split('-')
	account=request.form['account']
	amount=request.form['amount']
	description=request.form['description']
	currency=request.form['currency']

        if len(str(year))<4:
            year=2000+int(year)

        g.db.execute('UPDATE ENTRIES SET YEAR=?,MONTH=?,DAY=?,ACCOUNT=?,AMOUNT=?,CURRENCY=?,DESCRIPTION=? WHERE ID=?',[int(year),int(month),int(day),account,amount,currency,description,id_no])
        g.db.commit()
        return redirect(url_for('display.listall',no_rows_limit=20))

flaskaccounts/views/display.py
from flask import Blueprint,render_template,g,request,redirect,url_for,session
from flask.ext.login import login_required
from flask.ext.login import current_user

display=Blueprint('display',__name__)

@display.route('/show',defaults={'no_rows_limit':None})
@display.route('/show/<int:no_rows_limit>')
@login_required
def listall(no_rows_limit):
	#return render_template('body.html')
	dictionary={}
	#if session['logged_in']==False:
	#	return redirect(url_for('existinguser.login'))


	for row in g.db.execute('SELECT * FROM ENTRIES'):
		(ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
		dictionary[ID]=[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]
		max_rows=len(dictionary)

		if no_rows_limit!=None:
			min_row=max_rows-no_rows_limit
		else:
			min_row=0
	return render_template('display/main.html',output=dictionary,min_row=min_row,username=current_user.username,state2="active")

@display.route('/filter',methods=['POST'])
@login_required
def filter1():
	#if session['logged_in']==False:
	#	return redirect(url_for('existinguser.login'))
	if request.method=='POST':
		dictionary={}
		for row in g.db.execute('SELECT * FROM ENTRIES'):
			keyword=str(request.form['keyword'])
			(ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
			if keyword in DESCRIPTION.lower():
				dictionary[ID]=[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]

		return render_template('display/main.html',output=dictionary,min_row=0,username=current_user.username,state2="active",keyword=keyword)

@display.route('/sortdate',defaults={'no_rows':None})
@display.route('/sortdate/<int:no_rows>')
@login_required
def sortdate(no_rows):
	#if session['logged_in']==False:
	#	return redirect(url_for('existinguser.login'))

	dictionary={};dictionary2={}
	for row in g.db.execute('SELECT * FROM ENTRIES'):
		(ID,YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION)=row
		datesort=int(YEAR)*10000+int(MONTH)*100+DAY
		dictionary.setdefault(datesort,[]).append({ID:[YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION]})

		if no_rows!=None:
			min_row=0
		else:
			min_row=0

	return render_template('display/datesort.html',output=dictionary,no_rows=min_row,username=current_user.username,state4="active")

flaskaccounts/templates/display/datesort.html
{% extends "layout.html" %}
{% block body %}

<div class="page-header">
<h1>All Entries Sorted by Date</h1>
</div>

<table class="table table-condensed table-bordered">

<thead>
<tr>
<th>Date</th>
<th>Account</th>
<th>Description</th>
<th>Amount</th>
<th>Currency</th>
</tr>
</thead>

<tbody>
{%for date in output|sort%}
	{%for dictionary in output[date]%}
		{%for id in dictionary%}

			{%if dictionary[id][3]=='PREMIER' %}
				<tr class="info">
			{%elif dictionary[id][3]=='ADVANCED'%}
				<tr class="danger">
			{%elif dictionary[id][3]=='SAVINGS'%}
				<tr class="success">
			{%else%}
				<tr>
			{%endif%}
			<td>{{'%s/%s/%s'%(dictionary[id][2],dictionary[id][1],dictionary[id][0])}}</td>
			<td>{{dictionary[id][3]}}</td>
			<td>{{dictionary[id][6]}}</td>
			<td>{{dictionary[id][4]}}</td>
			<td>{{dictionary[id][5]}}</td>
			<td><a href="{{url_for('controller.delete_entry',id_no=id)}}">Delete</a></td>

		</tr>






		{%endfor%}
	{%endfor%}
{%endfor%}
</tbody>
</table>


<a href="{{url_for('controller.add_entry')}}{{a}}" role="button" class="btn btn-primary">Add</a>
<a href="{{url_for('controller.convert')}}{{a}}" role="button" class="btn btn-primary">Convert currency</a>
<a href="{{url_for('controller.transfer')}}{{a}}" role="button" class="btn btn-primary">Transfer</a>
{% endblock %}

flaskaccounts/templates/display/main.html
{% extends "layout.html" %}
{% block body %}

<div class="page-header">
<h1>Entries sorted by ID</h1>
	<form action="{{url_for('display.filter1')}}" method=POST>
	<div class="input-group">
		<input type="text" name="keyword" class="form-control" placeholder="Filter by keyword...">
		<span class="input-group-btn"><button class="btn btn-default" type="submit" value="submit">Filter</button></span>
	</div>
	</form>
</div>

{%if keyword%}
<h5>Filtered by keyword: <em>{{keyword}}</em></h5>
{%endif%}

<table class="table table-condensed table-bordered">

<thead>
<tr>
<th>Date</th>
<th>Account</th>
<th>Description</th>
<th>Amount</th>
<th>Currency</th>
</tr>
</thead>

<tbody>
{%for id in output.keys()[min_row:]|sort%}
{%if output[id][3]=='PREMIER' %}
<tr class="info">
{%elif output[id][3]=='ADVANCED'%}
<tr class="danger">
{%elif output[id][3]=='SAVINGS'%}
<tr class="success">
{%else%}
<tr>
{%endif%}
<td>{{'%s/%s/%s'%(output[id][2],output[id][1],output[id][0])}}</td>
<td>{{output[id][3]}}</td>
<td>{{output[id][6]}}</td>
<td>{{output[id][4]}}</td>
<td>{{output[id][5]}}</td>
<td><a href="{{url_for('controller.edit_entry',id_no=id)}}">Edit</a></td>
<td><a href="{{url_for('controller.delete_entry',id_no=id)}}">Delete</a></td>
</tr>
{%endfor%}
</tbody>
</table>

<a href="{{url_for('controller.add_entry')}}{{a}}" role="button" class="btn btn-primary">Add</a>
<a href="{{url_for('controller.convert')}}{{a}}" role="button" class="btn btn-primary">Convert currency</a>
<a href="{{url_for('controller.transfer')}}{{a}}" role="button" class="btn btn-primary">Transfer</a>

{% endblock %}